### PR TITLE
ARXIVOPS-548 fix web accessibility link

### PR DESCRIPTION
**Pull request by eawoods**
web accessibility link was returning blank, suspected it was due to the @ in the string.
Added unicode modifier, tests correctly in browser when running locally.

Not sure why this line's parameters are in double quotes and the rest are singles? Is there a subtlety in this designation that I'm missing or a reason to break consistency? I left it the way it was just in case. We seem to use singles and doubles throughout.

### CODE REVIEW

**Comment by erickpeirson** [comment]
@eawoods Is this ready for another look?

**Comment by eawoods** [comment]
Yes -- I had asked for help with it because the code changes are not working and I don't know why.
They don't throw errors, just...I can't get the code to show any effect (symptom: the link in question still doesn't resolve).

**Comment by erickpeirson** [comment]
Argh, sorry if I was blocking on this; will take a look later this morning.

**Comment by eawoods** [comment]
No worries and not blocking! I will be curious to know what is going on (probably a rookie mistake on my part).

- Liz

On Jan 17, 2019, at 8:05 AM, Erick <notifications@github.com<mailto:notifications@github.com>> wrote:


Argh, sorry if I was blocking on this; will take a look later this morning.

**Comment by erickpeirson** [comment]
Here's what gets rendered for me:

```html
<p class="help">If you have a disability and are having trouble accessing information
      on this website or need materials in an alternate format, contact
      <a href="mailto:web-accessibility@cornell.edu">web-accessibility@cornell.edu</a> for
       assistance.</p>
```

**Pull request merged**
