### PR TITLE
Pre-release merge for arxiv-base 0.16.9rc2

### PR DESCRIPTION
**Pull request by mhl10**

### CODE REVIEW

**Review by SBBCornell — APPROVED** [review]
looks good!

**Review by bdc34 — CHANGES_REQUESTED** [review]
Does SASS need to be built to CSS?

**Comment by mhl10** [comment]
> Does SASS need to be built to CSS?

@SBBCornell, Brian is referring to the changes in arxiv/base/static/sass/_custom.sass

**Comment by SBBCornell** [comment]
> > Does SASS need to be built to CSS?
> 
> @SBBCornell, Brian is referring to the changes in arxiv/base/static/sass/_custom.sass

@mhl10 @bdc34 I double checked the sass and css files and the change from _custom.sass is in arxivstyles.css, so that step did happen already.

**Review by bdc34 — APPROVED** [review]

**Pull request merged**
